language: go
sudo: false
go:
  # - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - tip
script:
  - sh sh/go_get_test.sh
  - OUT="$(go get -a)"; test -z "$OUT" || (echo "$OUT" && return 1)
  - OUT="$(gofmt -l -d ./)"; test -z "$OUT" || (echo "$OUT" && return 1)
  - OUT="$(go list ./... | grep -v /vendor/ | xargs -n 1 golint)"; test -z "$OUT" || (echo "$OUT" && return 1)
  - sh sh/go_dep.sh
  - sh sh/go_test.sh
  - go vet -v ./...
  - go build
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - go test -v -covermode=count -coverprofile=coverage.out
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
